apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openwhisk-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: openwhisk.kubernetes.riotfork.com
    http:
      paths:
      - backend:
          serviceName: controller
          servicePort: 8080
