ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: traefik
  hosts:
    - grafana.kubernetes.riotfork.com

adminUser: admin
adminPassword: kBTqPAn7YkrikLPgtns6uL8z

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards

dashboards:
  kubernetes-all-nodes:
    gnetId: 3131
    revision: 1
    datasource: Prometheus
  kubernetes-cluster-monitoring:
    gnetId: 3119
    revision: 2
    datasource: Prometheus
  kubernetes-node-exporter-full:
    gnetId: 3320
    revision: 1
    datasource: Prometheus
