serviceAccounts:
  alertmanager:
    create: false
  pushgateway:
    create: false

alertmanager:
  enabled: false

pushgateway:
  enabled: false

server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    server.ingress.hosts:
    - prometheus.kubernetes.riotfork.com
