serviceAccounts:
  alertmanager:
    create: false
  pushgateway:
    create: false

alertmanager:
  enabled: false

server:
  ingress:
    enabled: true
    hosts:
       - prometheus.192.168.99.100.xip.io

pushgateway:
  enabled: false
